<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>Meoiswa</Authors>
    <Company></Company>
    <Version>2.5.1.1</Version>
    <Description>Automatically adjusts the Battle Effects settings according to Party size.</Description>
    <PackageProjectUrl>https://github.com/meoiswa/ClarityInChaos</PackageProjectUrl>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="images\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
